### ISSUE TITLE
Does the minifier work for DOTLESS ? 

### ISSUE THREAD

**Issue by ekelvin** [isaaceindhoven/isaac-dotcms-minifier#2]
Its a question not an issue. Does the minifier work for less styling files compiled with DOTLESS?
If yes how can you use it for this case? 

For example if you use a Bootstrap theme you will get through DOTLESS/../...Bootsrap.css which is not minified. 
Can that file minified with this plugin?

**Comment by Xander-Steinmann** [comment]
Any CSS file can be minified. We try to minify as little as possible so most CSS files will not result into issues.
